version: '3.9'

services:
  api:
    build: ./backend
    command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 8088
    ports:
      - "8088:8088"
    environment:
      BACKEND_BASE_URL: "${BACKEND_BASE_URL}"
      UI_BASE_URL: "${UI_BASE_URL}"
